# -*- coding: utf-8 -*-
"""PA1_Machine_Learning_Gino_Zevallos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15LRBrI4x2HJJxs_jbbKBZMXJmAshhVUG
"""

import pandas as pd

url = "https://github.com/ginozevallosmonjaras/PA1-Machine-Learning/raw/refs/heads/main/diabetes.csv"

df = pd.read_csv(url)

df.head()

df.shape

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df["Outcome"].value_counts()

df["Outcome"].value_counts(normalize=True) * 100

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))

sns.histplot(data=df, x="Age", bins=20, kde=True)

plt.title("Distribución de la edad")
plt.xlabel("Edad")
plt.ylabel("Frecuencia")

plt.show()

"""### Interpretacion de la grafica 1

La grafica muestra la distribucion de las edades de las personas del
dataset, se ve una mayor concentracion de personas entre los 20 y
30 años aproximadamente, la distribucion muestra mayores datos concentracion en edades mas jovenes.
"""

plt.figure(figsize=(8,5))

sns.histplot(data=df, x="Glucose", bins=20, kde=True)

plt.title("Distribución de los niveles de glucosa")
plt.xlabel("Glucosa")
plt.ylabel("Frecuencia")

plt.show()

"""### Interpretacion del grafico 2

Se ve una distribucion de los niveles de glucosa en referencia a las personas del dataset, se ve que la mayor cantidad de registros esta entre los 90 y 140, tambine se puede ver que unos llegan incluso hasta los 150 a 200.
"""

plt.figure(figsize=(7,5))

sns.countplot(data=df, x="Outcome")

plt.title("Distribución de personas con y sin diabetes")
plt.xlabel("Resultado")
plt.ylabel("Cantidad")

plt.show()

"""### Interpretación de la gráfica 3

Se puede ver la cantidad de personas, segun el resultado de la variable outcome, las personas en que figuran en la columna 0, son las que no tienen diabetes y las de la columna 1, tienen diabetes, la mayoria esta en la columna 0, no tienen diabetes.
"""

plt.figure(figsize=(8,5))

sns.scatterplot(
    data=df,
    x="Age",
    y="Glucose",
    hue="Outcome"
)

plt.title("Relación entre edad y nivel de glucosa")
plt.xlabel("Edad")
plt.ylabel("Glucosa")

plt.show()

"""### Interpretacion de la grafica 4

Se muestra la relacion entre la edad y el nivel de glucosa, se puede ver que los registros de ambas categorias aparecen en diferentes edades y niveles de glucosa.
"""

plt.figure(figsize=(10,7))

sns.heatmap(
    df.corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Matriz de correlación")

plt.show()

"""### Interpretacion del grafico

La matriz de correlación permite observar la relacion entre las variables del dataset, se observa que Glucose presenta la mayor correlacion con Outcome, con un valor aproximado de 0.47.
"""

df_procesado = df.copy()

df_procesado.head()

columnas = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

(df_procesado[columnas] == 0).sum()

import numpy as np

columnas = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

df_procesado[columnas] = df_procesado[columnas].replace(0, np.nan)

df_procesado.isnull().sum()

for columna in columnas:
    df_procesado[columna] = df_procesado[columna].fillna(
        df_procesado[columna].median()
    )

df_procesado.isnull().sum()

X = df_procesado.drop("Outcome", axis=1)

y = df_procesado["Outcome"]

print("Características (X):")
print(X.head())

print("\nVariable objetivo (y):")
print(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Datos de entrenamiento:", X_train.shape)
print("Datos de prueba:", X_test.shape)

from sklearn.linear_model import LogisticRegression

modelo = LogisticRegression(max_iter=1000)

modelo.fit(X_train, y_train)

print("Modelo entrenado correctamente")

y_pred = modelo.predict(X_test)

print("Predicciones:")
print(y_pred[:20])

print("Valores reales:")
print(y_test.values[:20])

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy:", round(accuracy, 4))
print("Precision:", round(precision, 4))
print("Recall:", round(recall, 4))
print("F1 Score:", round(f1, 4))

"""### Evaluacion del modelo

El modelo de regresion logistica obtuvo un accuracy de 70.13%, quiere
decir que de cada 100 casos aproximadamente 70 fueron clasificados de forma correcta

La precision fue de 58.70%, lo que significa que cuando el modelo dijo que
una persona tenia diabetes, en varios casos esa prediccion fue correcta.

El recall fue de 50%, esto quiere decir que el modelo logro identificar
correctamente la mitad de los casos que realmente tenian diabetes.
"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["No diabetes", "Diabetes"]
)

disp.plot()

plt.title("Matriz de confusión")
plt.show()

"""### Interpretacion de la matriz de confusion

La matriz de confusion nos da los resultados de las predicciones de forma mas detallada, el modelo acerto 81 casos de personas que no tenian diabetes y 27 casos de personas que si tenian diabetes.

Tambien tuvo 19 casos en los que predijo diabetes cuando el resultado
real era no diabetes y 27 casos en los que predijo no diabetes cuando el
resultado real era diabetes.
"""